### ISSUE TITLE
Task completed section

### ISSUE THREAD

**Issue by vaishnav-sh** [vaishnav-sh/todo-app#1]
![completed](https://user-images.githubusercontent.com/68321987/135993211-49ae20c3-53cd-4ff8-b5a0-a9de6ffbe168.PNG)

**Comment by bhavya-vaid** [comment]
Could you describe the task?

**Comment by vaishnav-sh** [comment]
When I check the task that I have done, those tasks will be added to the list of completed tasks

**Comment by sandhyak-tech** [comment]
Shall i take up this task.. Could u plz assign this to me
@vaishnav-sh

**Comment by vaishnav-sh** [comment]
Go ahead

**Comment by vaishnav-sh** [comment]
Looks great. Change the arrow next to 'completed' so that it's pointing down when you click it.
