### ISSUE TITLE
UI/UX improvements

### ISSUE THREAD

**Issue by vaishnav-sh** [vaishnav-sh/todo-app#2]
redesign and modify the existing UI

**Comment by Jaspreet099** [comment]
### In Dark mode Input box should be in white color
![image](https://user-images.githubusercontent.com/75212002/136066248-9183c857-de54-4def-a863-f07909b66956.png)

**Comment by phoebeireland** [comment]
If no one has done this yet, may I be assigned to this, please?

**Comment by Jaspreet099** [comment]
@phoebeireland you can assigned issue to me I will fixed this

**Comment by vaishnav-sh** [comment]
Go ahead Jaspreet!

**Comment by vaishnav-sh** [comment]
> If no one has done this yet, may I be assigned to this, please?
> 

Sorry but he raised the issue first. Feel free to raise another issue and I'll assign you.
