### ISSUE TITLE
Implement LocalStorage to persist data between visits

### ISSUE THREAD

**Issue by sharedbyayla** [vaishnav-sh/todo-app#24]
Currently, all to-do tasks are lost when the page is refreshed or exited (either on purpose or by accident).
Implementing LocalStorage would be one solution to this problem-- one way of persisting data between visits. 

While there are other options as well, such as Firebase, I propose LocalStorage as a way of keeping the repository beginner-friendly.

**Comment by aexcode** [comment]
Hello! If this is an issue the team would like addressed, I would love to work on it.
