### ISSUE TITLE
Block Todos with no text to get added

### ISSUE THREAD

**Issue by Aashishkushwaha** [vaishnav-sh/todo-app#6]
Hi @vaishnav-sh , I've noticed that we can add the todo item without specifying any text. Ideally this should not happen in the application.

If you allow me then I can work on fixing this issue.

**Comment by Aashishkushwaha** [comment]
Hi @vaishnav-sh, I want to work on this issue, please assign it to me :)

**Comment by Aashishkushwaha** [comment]
@vaishnav-sh - also please add the hactoberfest label to this issue. 👍

**Comment by GeoBrodas** [comment]
Issue is solved here is my pull request!

https://github.com/vaishnav-sh/todo-app/pull/7#issue-1016391412

Happy hacking!

**Comment by Aashishkushwaha** [comment]
Hi @vaishnav-sh , I've raised the PR #8 . please review it and merge it .
